### ISSUE TITLE
LaTeX vs. Rmd discussion

### ISSUE THREAD

**Issue by paciorek** [jasa-acs/repro-template-dev#2]
I think we agreed to have the LaTeX template be primary and an Rmd template be secondary (and perhaps only after there is an JASA Rmd template?).

Let's discuss further here.

**Comment by stephaniehicks** [comment]
Yep, I think that makes sense. Also, I think it would be useful to have that latex template contributed to the `rticles` R package.

**Comment by paciorek** [comment]
Briefly from 2022-03-04 meeting: Julia will grab the existing JASA LaTeX template and include here (in a directory called manuscript). Not clear anything needs to be done to that template, but we might have ideas later.

Punt on Rmd template for now.

**Comment by jasa-acs** [comment]
I've removed manuscript.Rmd so as not to confuse users, since we are focusing on LaTeX for now.

**Comment by paciorek** [comment]
Leaving this open to remind us that we have a long-term goal to have an Rmd template.

**Comment by paciorek** [comment]
We agreed in 2022-06-03 meeting to close this as it's not a priority for now.
