### ISSUE TITLE
high-level / directory structure

### ISSUE THREAD

**Issue by paciorek** [jasa-acs/repro-template-dev#3]
Comments on the high-level (i.e., directory) structure? Please weigh in here.

One question we discussed a bit was how to distinguish code (and data) for simulations vs. real analyses and where to put code for generating simulated data.

**Comment by stephaniehicks** [comment]
I know @julia-wrobel had lots of thoughts here on the folder structure -- would love to hear her thoughts! 

In terms of things I think that make sense: 

- I think I agree with @kaneplusplus that it makes sense to remove the `\renv` folder (for now at least to keep things simple). 
- My broad sense is to keep the top folder structure fairly generic (e.g. not presume both (i) simulations, (ii) real analysis, (iii) both are there), but rather keep it something like `\analysis`

**Comment by paciorek** [comment]
Here was the consensus from meeting 2022-03-04:

High level directories:

- code
- data
- output
- manuscript

`code` is for underlying source code, e.g., the code that implements a method.
We expect that code to reproduce analyses would likely be in the root directory and would call out to functions/code in the `code` directory.

Add brief READMEs to each directory saying what they are about and suggestions for how one might use them.

@paciorek can make these changes.

**Comment by paciorek** [comment]
I've added brief READMEs to each directory. 

All, please comment/revise.
