### ISSUE TITLE
provide git init instructions in README

### ISSUE THREAD

**Issue by paciorek** [jasa-acs/repro-template-dev#6]
If we're going to tell users to fork and clone the repository and then remove the `.git` directory, we'll need specific instructions (e.g., linking to or extracting from [here](https://docs.github.com/en/get-started/importing-your-projects-to-github/importing-source-code-to-github/adding-locally-hosted-code-to-github)) for how to then create their own clean repository that doesn't have the history of the template repository. Related to that, is forking necessary/desired?

**Comment by jeff-goldsmith** [comment]
probably related to #4, too --

i think this depends on the target audience. if we're providing guidance to authors who are choosing to make their work available via git, then we may not need a ton of git-related background. but we should also be clear if that's our intended audience for this, and what other authors might get out of it (e.g. useful project organization, if not a git-centric workflow).

**Comment by paciorek** [comment]
I think the target audience definitely includes authors who are not git-focused, given we are providing useful project organization as you say.

**Comment by paciorek** [comment]
Stephanie's setting up of the repo as a template addresses all this.
